version: "3.9"

services:
  websocket-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: websocket-server
    ports:
      - "8081:8081"   # WebSocket server exposed on host:8081
    restart: unless-stopped

  websocket-client:
    image: nginx:alpine
    container_name: websocket-client
    volumes:
      - ./src/main/resources/static:/usr/share/nginx/html:ro
    ports:
      - "80:80"     # Serve static client on http://localhost:80
    restart: unless-stopped